name: bridgeclustering
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.13
  - numpy=1.22
  - matplotlib=3.2.1
  - pandas=1.0.3
  - scitkit-learn=0.22.1
  - pyod=1.0.0
  - hdbscan=0.8.28
  - networkx=2.6.3
  - pip:
    - python_algorithms=0.2.2
    - denmune=0.1.0